### ISSUE TITLE
Generate Using IDL-to-C++11 Mapping

### ISSUE THREAD

**Issue by mhutomop** [OpenDDS/node-opendds-rest-demo#6]
I'd like to generate shared library from IDL file using IDL-to-C++11 mapping and use the library in Node project using node-opendds. I need that because i want to use "@optional" annotation and as far as i know it should use IDL-to-C++11 mapping. I use OpenDDS-3.29.1.

Any help would be appreciated :)

**Comment by jrw972** [comment]
In this demo, the IDL is compiled into a shared library.  See idl/Game_Idl.mpc.

**Comment by sonndinh** [comment]
There is an example of using `@optional` in the xcdr test: https://github.com/OpenDDS/OpenDDS/blob/master/tests/DCPS/Compiler/xcdr/optional.idl for the IDL and https://github.com/OpenDDS/OpenDDS/blob/master/tests/DCPS/Compiler/xcdr/xcdr.mpc for the MPC file. The MPC file inherits `opendds_cxx11` for C++11 mapping. I think `@optional` will work with node-opendds but let us know if there's any issue.

**Comment by mitza-oci** [comment]
@mhutomop please let us know if it works with IDL `@optional`
